### ISSUE TITLE
 See if it is possible to lower server ping

### ISSUE THREAD

**Issue by bgauduch** [bgauduch/call-of-duty-2-docker-server#13]
20+ ms on local is too high, certainly linked to docker virtual network interface

**Comment by LSL1337** [comment]
i don't think this is the issue with this docker.
I have 1-3ms ping on locally hosted (not the same PC) server with this docker

**Comment by bgauduch** [comment]
I've tested again and the results are not homogenous. It might be related to my dev machine.

Thanks for the feedback @LSL1337 , closing this issue for now !
