### ISSUE TITLE
Can we run IPTables inside the container?

### ISSUE THREAD

**Issue by rainmak3rr** [bgauduch/call-of-duty-2-docker-server#2]
This works really well as a dedicated call of duty 2 server. However I need to find a way to run iptables inside the container to drop specific packets. Is there a way we can do this?

**Comment by bgauduch** [comment]
Hello @rainmak3rr !

Thanks for the nice feedback and for opening your issue 😃

Unfortunately, this Docker image is optimized and only run the server binary. As it is, you cannot launch iptable inside the container: their is indeed no linux kernel access as we are using the SCRATH base image.

But you still have a few options:
- build a new docker image from the Linux disrtibution of your choice to install and configure iptable;
- use iptable directly from the Host you are running Docker from

If by any chance you need iptable to do [this](https://killtube.org/showthread.php?1337-CoD2-Tutorial-How-to-make-your-cracked-server-show-up-in-the-master-list) specifically, you can use one of the cracked server binary in the [backup folder](https://github.com/bgauduch/call-of-duty-2-docker-server/tree/master/backups) to replace the official `cod2lnxded` in the `cod2server`folder, as mentioned in the project readme 😉

**Comment by rainmak3rr** [comment]
Hi @bgauduch 

Thank you for the reply :)

I tried running IPTables directly on the host but it does not seem to work, I tried this quickly and did not do any tcpdumps to see weather it's actually working. I might try this again. 

For now what I am doing is blocking the IP for the master server through the firewall and that works great, except that the server does not pop-up on the master list 😂 

Also, when I change the binary, for some reason it still does not work properly. This is the command I am using after changing the binary; **docker-compose up --build -d** That should rebuild the container and use the correct binary, or am I completely wrong?

Thank you!

**Comment by bgauduch** [comment]
My pleasure !

Yeah the thing is using iptable with Docker is not straightforward, as Docker manipulate it directly to provide network isolation. But you still can manipulate the DOCKER-USER chain to add custom rules : https://docs.docker.com/network/iptables/.

Blocking the master server IP is indeed quite radical as it prevent your server to appear on the public server list, but allow you to join with a cracked client if you now the public IP.

What errors do you get when changing the server binary ? 
You can check the following is correct : 
- You kept the same name for the server binary file: `cod2_lnxded``
- the file is executable, if not you can `chmod +x cod2_lnxded` ("permission denied" error)

Just for info, as per the forum thread I linked in my previous answer, you should use and rename the `cod2_lnxded_1_3_nodelay_va_loc` server binary.

**Comment by rainmak3rr** [comment]
Perfect, that link will help me :)

The server comes up when I change the cod2_Inxded with the nodelay one, but for some reason it will still not allow people to join the server who have an invalid key. That is why I thought I was not building it correctly, and as a work around I blocked the master list IP from the router which makes the server accessible but not on the master list. 

Thank you for the help, I'll figure it out! 👍

**Comment by bgauduch** [comment]
Good 👍
Have fun with iptable 😉 

Oh okay !
Did you try the using the `cod2_lnxded_1_3_patch_va_loc` server binary ?  I made a mistake on the binary name and updated my previous message.

You are welcome ! Hope you will eventually make it work 😉 
Please let me know if you need any more help or if it is working, so I can close this issue.

**Comment by bgauduch** [comment]
Hey @rainmak3rr !

Just for the record I've added the libcod library to the server and updated the doc (see [this answer](https://killtube.org/showthread.php?1337-CoD2-Tutorial-How-to-make-your-cracked-server-show-up-in-the-master-list&p=16844&viewfull=1#post16844) from Mitch on Killtube) and set `cod2_lnxded_1_3_nodelay_va_loc` as the default server binary.

You might want to give it a try :wink:

Anyway, I am closing this issue for now as all the iptable config is not directly related to this project.
Feel free to open a new one if needed.
Best regards !

**Comment by rainmak3rr** [comment]
Thank you! And may your frags forever stay high 👍
