### ISSUE TITLE
Kicked from server when PunkBuster is enabled

### ISSUE THREAD

**Issue by bgauduch** [bgauduch/call-of-duty-2-docker-server#42]
get kicked after a while when PunkBuster is enabled on the server.

PB version: A1383 C2.208

Error log:
```sh
cod2_server_1  | 0:Phantom PunkBuster kicked player 'Phantom' (for 0 minutes) ... This PB Server Requires (A1383 C2.208) - Error loading pbag
cod2_server_1  | PunkBuster Server: Kick Command Issued (This PB Server Requires (A1383 C2.208) - Error loading pbag) for (slot#1) 192.168.192.1:37817  Phant
```

**Comment by LSL1337** [comment]
you need the latest client side files on your pb folder as well
this is not a docker issue.

**Comment by bgauduch** [comment]
@LSL1337 indeed you are right ! 
I just wanted to trace the issue since I'm sure the question will be asked after adding PB to the images 😉
