### ISSUE TITLE
Deploying to aws ec2 instance

### ISSUE THREAD

**Issue by fcakyon** [bgauduch/call-of-duty-2-docker-server#45]
Thanks a lot for arranging all the dockerfiles and images. 

Would you mind telling me more on how to host a cod2 server on cloud using these dockerfiles? Can I deploy them on ec2 instance with 4gb ram, would that amount of sources sufficient?

Bests

**Comment by bgauduch** [comment]
Hello @fcakyon ! Thanks a lot for the feedback, much appreciated 👍 

As described in the "Requirements" section of the readme, you can host a cod2 server on anything with:
* an x86_64 architecture;
* Docker daemon installed (other container runtimes not tested with this image yet);
* docker-compose, to use the provided compose files and configuration

So you should be able to deploy a cod2 server on EC2 using the provided images build from this repository. I'm interested in the feedback if you do so !

This is quite an old game so it's low on CPU and memory. What you are looking for is a good bandwidth to get a low server ping and allow multiple players to join without trouble. I believe you are covered using a small EC2 instance in AWS infrastructure 😉 

I did host a server using OVH VPS back in the days, it was more than enougth.

I've never monitored much, a good start could be a simple `docker container stats` on you local machine. Here is mine for instance:
```sh
CONTAINER ID        NAME                                         CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
a10261edf7d1        call-of-duty-2-docker-server_cod2_server_1   13.61%              49.63MiB / 7.777GiB   0.62%               2.72kB / 2.94kB     0B / 0B             1
````

Also be aware that some server settings might have an impact on CPU usage (`sv_maxrate` and `sv_fps` for instance), you might want to tweak them for your needs.

**Comment by fcakyon** [comment]
thanks a lot for the fast response, will return with my feedback!

**Comment by bgauduch** [comment]
You are welcome @fcakyon !
Have fun settings this up 🚀

**Comment by fcakyon** [comment]
btw what is the unit of "sv_maxrate", is it in bytes?

**Comment by bgauduch** [comment]
@fcakyon I had absolutely no idea before a quick search.

According to [this site](https://www.olddogvt.net/cod-firewall/) providing a rule of thumb for `sv_maxrate` calculation,  it seem's to be `bytes/s`!

Will add the unit to the config file comment 😉
