### ISSUE TITLE
config file name

### ISSUE THREAD

**Issue by fcakyon** [bgauduch/call-of-duty-2-docker-server#47]
Hello again,

[In the readme](https://github.com/bgauduch/call-of-duty-2-docker-server/blob/master/README.md#setup-the-server) it says "Edit the config file located in cod2server/main/config.cfg to suits your needs" but I only find "cod2server/main/server_mp.cfg".

Is "config.cfg" in readme same with "server_mp.cfg" currently present in "cod2server/main/" ?

**Comment by bgauduch** [comment]
Thanks for pointing out this typo @fcakyon, the `config.cfg` in the readme refer indeed to the `server_mp.cfg` in the main folder. 

The readme was simply not updated correctly after the config file was renamed, I will update this right away.
