### ISSUE TITLE
Can’t make it work on Windows 

### ISSUE THREAD

**Issue by andrebore** [bgauduch/call-of-duty-2-docker-server#55]
Hello there!
I’ve got a strage behavior: I was able to make it run in Linux without any problem but I couldn’t make it work on Windows. Same docker-compose file just with different paths for the main and game folders. 
Log says 0 iwd found. I can assure the main folder is being mounted in the same path as Linux and it is readable

**Comment by bgauduch** [comment]
Hello @andrebore, thanks for opening this issue !
I believe this might be a permission issue as in #49, that being said I never tried to launch the server on windows.

If you really need to use windows as a base OS, you might want to try using an unix WSL and see how it goes !

**Comment by bgauduch** [comment]
@andrebore As a temporary fix I did remove the non-root user causing file permissions issues when mounting game files (see #59 for more details).

You should now be able to use latest image on windows without troubles 😉 

Closing this issue, do not hesitate to reopen or fil a new one if you get in any other troubles !
