### ISSUE TITLE
Time seems to go to fast

### ISSUE THREAD

**Issue by HenkVanMaanen** [bgauduch/call-of-duty-2-docker-server#67]
I have this problem that the respawn happens too fast, you see `spawn in` 12 seconds... 11 seconds... and then I respawn instantly in ctf for example while the settings are set to 5 seconds respawn delay. Same with search and destroy, after exactly 24 seconds the round ends and says 'time expired'. Anybody knows how to solve this?

```// Capture the Flag
set scr_ctf_scorelimit "5"
set scr_ctf_timelimit "0"
set scr_ctf_respawndelay "5"

// Deathmatch Settings
set scr_dm_scorelimit "30"
set scr_dm_timelimit "10"

// Headquaters
set scr_hq_scorelimit "450"
set scr_hq_timelimit "0"
set scr_hq_respawndelay "5"

// Search and Destroy Settings
set scr_sd_graceperiod "15"
set scr_sd_roundlength "4"
set scr_sd_roundlimit "0"
set scr_sd_scorelimit "10"
set scr_sd_timelimit "0"
set scr_sd_bombtimer "60"

// Team Deathmatch Settings
set scr_tdm_scorelimit "100"
set scr_tdm_timelimit "10"
```

**Comment by HenkVanMaanen** [comment]
To answer my own question, it's the sv_fps value that speeds up the time. I thought it was a tickrate setting, it is but it will change the timings of things too

**Comment by bgauduch** [comment]
Hello @HenkVanMaanen !

Thanks for opening this issue and resolving it at the same time 💪 
Sorry I didn't get the chance to answer you or test before.

I had no idea that the `sv_fps` parameter could have an impact on server time, that's strange !
At first I would have say that some timezone config could be missing inside the container, I will definitely try to dig deeper.

Please let me know if this happen again.
In the meantime, happy gaming 😉
