### ISSUE TITLE
2

### ISSUE THREAD

**Issue by asem12300** [bgauduch/call-of-duty-2-docker-server#90]
COD MP 1.4 build win-x86 Apr 13 2004
----- FS_Startup -----
Current language: english
Current search path:
D:\مجلد جديد ?(2)?\ipcgames.com_call_of_duty_united_offensive/main

File Handles:
----------------------
0 files in pk3 files
ERROR: No languages available because no localized assets were found
ERROR: No languages available because no localized assets were found
----- CL_Shutdown -----
-----------------------
Hunk_Clear: reset the hunk ok
Couldn't load default_mp.cfg.  Make sure Call of Duty is run from the correct folder.

**Comment by bgauduch** [comment]
Hello @asem12300 , not sure what you are trying to do here as the log shows cod1.4 and united offensive.

This project support cod2 only, did you follow the readme instructions ?

**Comment by bgauduch** [comment]
Closing issue as not related to the correct game version.
